services:
  - type: web
    name: banking-analysis
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1
    envVars:
      - key: GROQ_API_KEY_BK
        sync: false
      - key: PORT
        value: 10000
