services:
  - type: web
    name: banking-analysis
    runtime: docker          # Chú ý dòng này
    dockerfilePath: Dockerfile
    plan: free               # Hoặc gói bạn đang dùng
    envVars:
      - key: GROQ_API_KEY_BK
        sync: false
      - key: PORT
        value: 10000
